controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    effort_controller:
      type: effort_controllers/JointGroupEffortController

trajectory_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
    joints:
      - joint_1

    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    open_loop_control: true
    set_last_command_interface_value_as_state_on_activation: false

velocity_controller:
  ros__parameters:
    command_interfaces:
      - velocity
    state_interfaces:
      - velocity  
    joints:
      - joint_1

effort_controller:
  ros__parameters:
    joints:
      - joint_1
