# Configuration file for Maxon EPOS3 drive
vendor_id: 0x00100000
product_id: 0x000c0112
assign_activate: 0x0300 # DC Synch register
auto_fault_reset: false # true = automatic fault reset, false = fault reset on rising edge command interface "reset_fault"
sdo: # sdo data to be transferred at drive startup
  # - { index: 0x60C2, sub_index: 1, type: int8, value: 10 } # Set interpolation time for cyclic modes to 10 ms
  # - { index: 0x60C2, sub_index: 2, type: int8, value: -3 } # Set base 10-3s
rpdo: # RxPDO = receive PDO 4 Mapping
  - index: 0x1600
    channels:
      - { index: 0x6040, sub_index: 0, type: uint16, default: 0 } # Control word
      - {
          index: 0x607a,
          sub_index: 0,
          type: int32,
          command_interface: position,
          default: .nan,
        } # Target position
      - { index: 0x60b8, sub_index: 0, type: uint16, default: 0 } # Touch Probe Function
      - { index: 0x60fe, sub_index: 1, type: uint32, default: 0 } # 物理输出
tpdo: # TxPDO = transmit PDO 4 Mapping
  - index: 0x1A00
    channels:
      - { index: 0x603f, sub_index: 0, type: uint16 } # 错误码
      - { index: 0x6041, sub_index: 0, type: uint16 } # Status word
      - { index: 0x6064, sub_index: 0, type: int32, state_interface: position } # Position actual value
      - { index: 0x6077, sub_index: 0, type: int16, state_interface: effort } # Torque actual value
      - { index: 0x60f4, sub_index: 0, type: int32 } # 位置偏差
      - { index: 0x60b9, sub_index: 0, type: int16 } # Touch Probe Status
      - { index: 0x60ba, sub_index: 0, type: int32 } # Touch Probe Position 1 Positive Value
      - { index: 0x60bc, sub_index: 0, type: int32 } # 探针2上升沿位置反馈
      - { index: 0x60fd, sub_index: 0, type: uint32 } # DI状态
